<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LowonganSeeder extends Seeder
{
    public function run(): void
    {

        $maxPerusahaan = 10;
        $minJenisPelaksanaan = 6;
        $maxJenisPelaksanaan = 8;

        DB::table('lowongan')->insert([
            [
                'id_perusahaan'         => 1,
                'nama_posisi'           => 'Frontend Developer Intern',
                'deskripsi'             => 'Mengembangkan tampilan antarmuka web dengan HTML, CSS, dan JavaScript.',
                'id_bidang_keahlian'    => 15,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 3,
                'persyaratan'           => 'Menguasai HTML, CSS, dan JavaScript dasar.',
                'tanggal_buka'          => '2025-06-01',
                'tanggal_tutup'         => '2025-06-30',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id_perusahaan'         => 1,
                'nama_posisi'           => 'Backend Developer Intern',
                'deskripsi'             => 'Mengembangkan API dan logika server-side menggunakan PHP dan Laravel.',
                'id_bidang_keahlian'    => 14,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 2,
                'persyaratan'           => 'Menguasai dasar PHP dan database MySQL.',
                'tanggal_buka'          => '2025-06-05',
                'tanggal_tutup'         => '2025-07-05',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id_perusahaan'         => 2,
                'nama_posisi'           => 'Mobile Developer Intern',
                'deskripsi'             => 'Membuat aplikasi Android menggunakan Kotlin atau Flutter.',
                'id_bidang_keahlian'    => 18,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 2,
                'persyaratan'           => 'Paham dasar Android Studio atau Flutter.',
                'tanggal_buka'          => '2025-07-01',
                'tanggal_tutup'         => '2025-07-31',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id_perusahaan'         => 2,
                'nama_posisi'           => 'UI/UX Designer Intern',
                'deskripsi'             => 'Mendesain antarmuka aplikasi dan prototyping dengan Figma.',
                'id_bidang_keahlian'    => 29,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 1,
                'persyaratan'           => 'Mampu menggunakan Figma atau Adobe XD.',
                'tanggal_buka'          => '2025-06-10',
                'tanggal_tutup'         => '2025-07-10',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id_perusahaan'         => 3,
                'nama_posisi'           => 'Data Analyst Intern',
                'deskripsi'             => 'Mengolah data menggunakan Excel dan SQL.',
                'id_bidang_keahlian'    => 41,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 2,
                'persyaratan'           => 'Menguasai dasar Excel dan query SQL.',
                'tanggal_buka'          => '2025-06-15',
                'tanggal_tutup'         => '2025-07-15',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id_perusahaan'         => 3,
                'nama_posisi'           => 'DevOps Intern',
                'deskripsi'             => 'Membantu proses deployment dan manajemen CI/CD.',
                'id_bidang_keahlian'    => 17,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 1,
                'persyaratan'           => 'Paham Git dan konsep dasar DevOps.',
                'tanggal_buka'          => '2025-06-20',
                'tanggal_tutup'         => '2025-07-20',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id_perusahaan'         => 1,
                'nama_posisi'           => 'Frontend Developer Intern',
                'deskripsi'             => 'Mengembangkan tampilan antarmuka web dengan HTML, CSS, dan JavaScript.',
                'id_bidang_keahlian'    => 15,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 3,
                'persyaratan'           => 'Menguasai HTML, CSS, dan JavaScript dasar.',
                'tanggal_buka'          => '2025-06-01',
                'tanggal_tutup'         => '2025-06-30',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id_perusahaan'         => 1,
                'nama_posisi'           => 'Backend Developer Intern',
                'deskripsi'             => 'Mengembangkan API dan logika server-side menggunakan PHP dan Laravel.',
                'id_bidang_keahlian'    => 14,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 2,
                'persyaratan'           => 'Menguasai dasar PHP dan database MySQL.',
                'tanggal_buka'          => '2025-06-05',
                'tanggal_tutup'         => '2025-07-05',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id_perusahaan'         => 2,
                'nama_posisi'           => 'Mobile App Developer Intern',
                'deskripsi'             => 'Membantu pengembangan aplikasi Android dan iOS.',
                'id_bidang_keahlian'    => 18,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 2,
                'persyaratan'           => 'Menguasai dasar Kotlin atau Swift.',
                'tanggal_buka'          => '2025-07-01',
                'tanggal_tutup'         => '2025-07-31',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id_perusahaan'         => 3,
                'nama_posisi'           => 'Data Analyst Intern',
                'deskripsi'             => 'Menganalisa data menggunakan Excel dan SQL.',
                'id_bidang_keahlian'    => 42,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 1,
                'persyaratan'           => 'Paham dasar statistik dan SQL.',
                'tanggal_buka'          => '2025-06-15',
                'tanggal_tutup'         => '2025-07-15',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id_perusahaan'         => 4,
                'nama_posisi'           => 'DevOps Intern',
                'deskripsi'             => 'Mendukung pengelolaan deployment otomatis dan server.',
                'id_bidang_keahlian'    => 17,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 1,
                'persyaratan'           => 'Mengerti dasar Linux dan CI/CD.',
                'tanggal_buka'          => '2025-05-20',
                'tanggal_tutup'         => '2025-06-20',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id_perusahaan'         => 2,
                'nama_posisi'           => 'UI/UX Designer Intern',
                'deskripsi'             => 'Membantu desain antarmuka dan pengalaman pengguna.',
                'id_bidang_keahlian'    => 29,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 2,
                'persyaratan'           => 'Mahir menggunakan Figma atau Adobe XD.',
                'tanggal_buka'          => '2025-06-10',
                'tanggal_tutup'         => '2025-07-10',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id_perusahaan'         => 5,
                'nama_posisi'           => 'Quality Assurance Intern',
                'deskripsi'             => 'Melakukan pengujian aplikasi dan dokumentasi bug.',
                'id_bidang_keahlian'    => 25,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 2,
                'persyaratan'           => 'Teliti dan paham testing dasar.',
                'tanggal_buka'          => '2025-07-01',
                'tanggal_tutup'         => '2025-07-31',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id_perusahaan'         => 3,
                'nama_posisi'           => 'Cybersecurity Intern',
                'deskripsi'             => 'Mendukung pengamanan sistem dan monitoring.',
                'id_bidang_keahlian'    => 23,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 1,
                'persyaratan'           => 'Paham dasar keamanan jaringan.',
                'tanggal_buka'          => '2025-06-25',
                'tanggal_tutup'         => '2025-07-25',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id_perusahaan'         => 1,
                'nama_posisi'           => 'Project Management Intern',
                'deskripsi'             => 'Mendukung koordinasi dan pengelolaan proyek IT.',
                'id_bidang_keahlian'    => 36,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 1,
                'persyaratan'           => 'Mampu berkomunikasi dan mengatur jadwal.',
                'tanggal_buka'          => '2025-06-01',
                'tanggal_tutup'         => '2025-06-30',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id_perusahaan'         => 4,
                'nama_posisi'           => 'Graphic Designer Intern',
                'deskripsi'             => 'Membantu desain visual marketing dan branding.',
                'id_bidang_keahlian'    => 40,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 2,
                'persyaratan'           => 'Mahir Adobe Photoshop dan Illustrator.',
                'tanggal_buka'          => '2025-07-05',
                'tanggal_tutup'         => '2025-08-05',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id_perusahaan'         => 5,
                'nama_posisi'           => 'Cloud Engineer Intern',
                'deskripsi'             => 'Membantu pengelolaan infrastruktur cloud (AWS/GCP).',
                'id_bidang_keahlian'    => 24,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 1,
                'persyaratan'           => 'Dasar AWS atau Google Cloud Platform.',
                'tanggal_buka'          => '2025-06-10',
                'tanggal_tutup'         => '2025-07-10',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id_perusahaan'         => 2,
                'nama_posisi'           => 'Machine Learning Intern',
                'deskripsi'             => 'Membantu pengembangan model pembelajaran mesin.',
                'id_bidang_keahlian'    => 22,
                'id_jenis_pelaksanaan'  => random_int($minJenisPelaksanaan, $maxJenisPelaksanaan),
                'id_durasi_magang'      => random_int(4, 5),
                'kuota'                 => 1,
                'persyaratan'           => 'Paham Python dan algoritma ML dasar.',
                'tanggal_buka'          => '2025-06-15',
                'tanggal_tutup'         => '2025-07-15',
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
        ]);

    }
}
