<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LowonganSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('lowongan')->insert([
            [
                'id_perusahaan' => 1,
                'nama_posisi' => 'Frontend Developer Intern',
                'deskripsi' => 'Mengembangkan tampilan antarmuka web dengan HTML, CSS, dan JavaScript.',
                'id_jenis_pelaksanaan' => 6,
                'id_durasi_magang' => 4,
                'kuota' => 3,
                'persyaratan' => 'Menguasai HTML, CSS, dan JavaScript dasar.',
                'tanggal_buka' => '2025-06-01',
                'tanggal_tutup' => '2025-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 1,
                'nama_posisi' => 'Backend Developer Intern',
                'deskripsi' => 'Mengembangkan API dan logika server-side menggunakan PHP dan Laravel.',
                'id_jenis_pelaksanaan' => 7,
                'id_durasi_magang' => 5,
                'kuota' => 2,
                'persyaratan' => 'Menguasai dasar PHP dan database MySQL.',
                'tanggal_buka' => '2025-06-05',
                'tanggal_tutup' => '2025-07-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 2,
                'nama_posisi' => 'Mobile Developer Intern',
                'deskripsi' => 'Membuat aplikasi Android menggunakan Kotlin atau Flutter.',
                'id_jenis_pelaksanaan' => 8,
                'id_durasi_magang' => 4,
                'kuota' => 2,
                'persyaratan' => 'Paham dasar Android Studio atau Flutter.',
                'tanggal_buka' => '2025-07-01',
                'tanggal_tutup' => '2025-07-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 2,
                'nama_posisi' => 'UI/UX Designer Intern',
                'deskripsi' => 'Mendesain antarmuka aplikasi dan prototyping dengan Figma.',
                'id_jenis_pelaksanaan' => 6,
                'id_durasi_magang' => 5,
                'kuota' => 1,
                'persyaratan' => 'Mampu menggunakan Figma atau Adobe XD.',
                'tanggal_buka' => '2025-06-10',
                'tanggal_tutup' => '2025-07-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 3,
                'nama_posisi' => 'Data Analyst Intern',
                'deskripsi' => 'Mengolah data menggunakan Excel dan SQL.',
                'id_jenis_pelaksanaan' => 7,
                'id_durasi_magang' => 4,
                'kuota' => 2,
                'persyaratan' => 'Menguasai dasar Excel dan query SQL.',
                'tanggal_buka' => '2025-06-15',
                'tanggal_tutup' => '2025-07-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 3,
                'nama_posisi' => 'DevOps Intern',
                'deskripsi' => 'Membantu proses deployment dan manajemen CI/CD.',
                'id_jenis_pelaksanaan' => 8,
                'id_durasi_magang' => 5,
                'kuota' => 1,
                'persyaratan' => 'Paham Git dan konsep dasar DevOps.',
                'tanggal_buka' => '2025-06-20',
                'tanggal_tutup' => '2025-07-20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 4,
                'nama_posisi' => 'Graphic Designer Intern',
                'deskripsi' => 'Membantu desain visual marketing dan branding.',
                'id_jenis_pelaksanaan' => 6,
                'id_durasi_magang' => 4,
                'kuota' => 2,
                'persyaratan' => 'Mahir Adobe Photoshop dan Illustrator.',
                'tanggal_buka' => '2025-07-05',
                'tanggal_tutup' => '2025-08-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 5,
                'nama_posisi' => 'Cloud Engineer Intern',
                'deskripsi' => 'Membantu pengelolaan infrastruktur cloud (AWS/GCP).',
                'id_jenis_pelaksanaan' => 7,
                'id_durasi_magang' => 5,
                'kuota' => 1,
                'persyaratan' => 'Dasar AWS atau Google Cloud Platform.',
                'tanggal_buka' => '2025-06-10',
                'tanggal_tutup' => '2025-07-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 2,
                'nama_posisi' => 'Machine Learning Intern',
                'deskripsi' => 'Membantu pengembangan model pembelajaran mesin.',
                'id_jenis_pelaksanaan' => 8,
                'id_durasi_magang' => 4,
                'kuota' => 1,
                'persyaratan' => 'Paham Python dan algoritma ML dasar.',
                'tanggal_buka' => '2025-06-15',
                'tanggal_tutup' => '2025-07-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 3,
                'nama_posisi' => 'Cybersecurity Intern',
                'deskripsi' => 'Menangani analisis keamanan jaringan dan sistem.',
                'id_jenis_pelaksanaan' => 6,
                'id_durasi_magang' => 5,
                'kuota' => 1,
                'persyaratan' => 'Pengetahuan dasar jaringan dan keamanan sistem.',
                'tanggal_buka' => '2025-06-18',
                'tanggal_tutup' => '2025-07-18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 1,
                'nama_posisi' => 'Project Management Intern',
                'deskripsi' => 'Membantu koordinasi tim proyek dan pembuatan jadwal.',
                'id_jenis_pelaksanaan' => 7,
                'id_durasi_magang' => 4,
                'kuota' => 1,
                'persyaratan' => 'Mampu mengelola waktu dan komunikasi tim.',
                'tanggal_buka' => '2025-06-25',
                'tanggal_tutup' => '2025-07-25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 4,
                'nama_posisi' => 'Content Writer Intern',
                'deskripsi' => 'Menulis artikel dan konten promosi perusahaan.',
                'id_jenis_pelaksanaan' => 8,
                'id_durasi_magang' => 5,
                'kuota' => 2,
                'persyaratan' => 'Kemampuan menulis dan riset topik.',
                'tanggal_buka' => '2025-07-01',
                'tanggal_tutup' => '2025-07-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 5,
                'nama_posisi' => 'QA Tester Intern',
                'deskripsi' => 'Melakukan pengujian aplikasi dan dokumentasi bug.',
                'id_jenis_pelaksanaan' => 6,
                'id_durasi_magang' => 4,
                'kuota' => 2,
                'persyaratan' => 'Teliti dan paham cara kerja aplikasi.',
                'tanggal_buka' => '2025-06-12',
                'tanggal_tutup' => '2025-07-12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 4,
                'nama_posisi' => 'Digital Marketing Intern',
                'deskripsi' => 'Membantu kampanye digital dan analisis performa iklan.',
                'id_jenis_pelaksanaan' => 7,
                'id_durasi_magang' => 5,
                'kuota' => 2,
                'persyaratan' => 'Paham media sosial dan tools analitik.',
                'tanggal_buka' => '2025-06-22',
                'tanggal_tutup' => '2025-07-22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 3,
                'nama_posisi' => 'Business Analyst Intern',
                'deskripsi' => 'Analisis kebutuhan bisnis dan pengumpulan data.',
                'id_jenis_pelaksanaan' => 8,
                'id_durasi_magang' => 4,
                'kuota' => 1,
                'persyaratan' => 'Komunikatif dan logis.',
                'tanggal_buka' => '2025-06-15',
                'tanggal_tutup' => '2025-07-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 2,
                'nama_posisi' => 'System Administrator Intern',
                'deskripsi' => 'Membantu konfigurasi dan pemeliharaan server.',
                'id_jenis_pelaksanaan' => 6,
                'id_durasi_magang' => 5,
                'kuota' => 1,
                'persyaratan' => 'Paham Linux dan administrasi sistem.',
                'tanggal_buka' => '2025-07-03',
                'tanggal_tutup' => '2025-08-03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 1,
                'nama_posisi' => 'AI Research Intern',
                'deskripsi' => 'Membantu eksperimen dan riset model AI baru.',
                'id_jenis_pelaksanaan' => 7,
                'id_durasi_magang' => 5,
                'kuota' => 1,
                'persyaratan' => 'Menguasai Python dan framework AI.',
                'tanggal_buka' => '2025-06-10',
                'tanggal_tutup' => '2025-07-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 5,
                'nama_posisi' => 'Game Developer Intern',
                'deskripsi' => 'Membantu pembuatan game dengan Unity atau Unreal Engine.',
                'id_jenis_pelaksanaan' => 8,
                'id_durasi_magang' => 4,
                'kuota' => 2,
                'persyaratan' => 'Paham C# atau C++ dan engine game.',
                'tanggal_buka' => '2025-06-28',
                'tanggal_tutup' => '2025-07-28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 4,
                'nama_posisi' => 'Social Media Intern',
                'deskripsi' => 'Menangani konten dan engagement di media sosial.',
                'id_jenis_pelaksanaan' => 6,
                'id_durasi_magang' => 4,
                'kuota' => 2,
                'persyaratan' => 'Kreatif dan aktif di media sosial.',
                'tanggal_buka' => '2025-07-01',
                'tanggal_tutup' => '2025-07-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 5,
                'nama_posisi' => 'Technical Writer Intern',
                'deskripsi' => 'Membuat dokumentasi teknis produk dan panduan penggunaan sistem.',
                'id_jenis_pelaksanaan' => 7,
                'id_durasi_magang' => 4,
                'kuota' => 1,
                'persyaratan' => 'Mampu menulis dokumentasi teknis dengan baik dan memahami istilah IT.',
                'tanggal_buka' => '2025-07-05',
                'tanggal_tutup' => '2025-08-05',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
