<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PengalamanSeeder extends Seeder
{
    public function run()
    {
        DB::table('pengalaman')->insert([
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720172')->value('id_mahasiswa'),
                'nama_posisi' => 'Asisten Praktikum',
                'perusahaan' => 'Laboratorium Pemrograman',
                'tanggal_mulai' => '2023-03-01',
                'tanggal_selesai' => '2023-07-31',
                'deskripsi' => 'Membantu dosen dalam kegiatan praktikum dan memeriksa tugas mahasiswa.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720172')->value('id_mahasiswa'),
                'nama_posisi' => 'Magang Backend Developer',
                'perusahaan' => 'PT Inovasi Digital',
                'tanggal_mulai' => '2024-01-10',
                'tanggal_selesai' => '2024-04-10',
                'deskripsi' => 'Mengembangkan REST API menggunakan Laravel untuk kebutuhan proyek internal.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720182')->value('id_mahasiswa'),
                'nama_posisi' => 'Web Developer',
                'perusahaan' => 'PT Teknologi Mandiri',
                'tanggal_mulai' => '2023-06-15',
                'tanggal_selesai' => '2023-08-30',
                'deskripsi' => 'Membuat dan memelihara website profil perusahaan menggunakan HTML, CSS, dan JavaScript.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720182')->value('id_mahasiswa'),
                'nama_posisi' => 'Freelance UI Designer',
                'perusahaan' => null,
                'tanggal_mulai' => '2022-11-01',
                'tanggal_selesai' => '2023-01-31',
                'deskripsi' => 'Mendesain antarmuka pengguna untuk aplikasi mobile menggunakan Figma.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720234')->value('id_mahasiswa'),
                'nama_posisi' => 'Data Entry Intern',
                'perusahaan' => 'CV DataDigital',
                'tanggal_mulai' => '2023-02-01',
                'tanggal_selesai' => '2023-04-30',
                'deskripsi' => 'Menginput data pelanggan ke dalam sistem perusahaan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720234')->value('id_mahasiswa'),
                'nama_posisi' => 'Panitia Seminar IT',
                'perusahaan' => null,
                'tanggal_mulai' => '2022-09-10',
                'tanggal_selesai' => '2022-10-10',
                'deskripsi' => 'Bertanggung jawab atas pendaftaran peserta dan publikasi acara.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720256')->value('id_mahasiswa'),
                'nama_posisi' => 'Junior Programmer Intern',
                'perusahaan' => 'PT Solusi Digital',
                'tanggal_mulai' => '2023-07-01',
                'tanggal_selesai' => '2023-09-30',
                'deskripsi' => 'Membantu pengembangan sistem informasi berbasis web.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720256')->value('id_mahasiswa'),
                'nama_posisi' => 'Volunteer IT Support',
                'perusahaan' => 'Yayasan Pendidikan Anak Bangsa',
                'tanggal_mulai' => '2022-12-01',
                'tanggal_selesai' => '2023-02-28',
                'deskripsi' => 'Menangani permasalahan teknis komputer dan jaringan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720187')->value('id_mahasiswa'),
                'nama_posisi' => 'Staf Dokumentasi',
                'perusahaan' => 'UKM Robotika',
                'tanggal_mulai' => '2023-01-01',
                'tanggal_selesai' => '2023-06-30',
                'deskripsi' => 'Mengelola dokumentasi kegiatan dan membuat laporan tahunan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720187')->value('id_mahasiswa'),
                'nama_posisi' => 'Content Creator',
                'perusahaan' => null,
                'tanggal_mulai' => '2022-10-01',
                'tanggal_selesai' => '2023-01-01',
                'deskripsi' => 'Membuat konten edukatif seputar teknologi untuk media sosial.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720038')->value('id_mahasiswa'),
                'nama_posisi' => 'Event Organizer Staff',
                'perusahaan' => 'Himpunan Mahasiswa TI',
                'tanggal_mulai' => '2023-05-01',
                'tanggal_selesai' => '2023-08-31',
                'deskripsi' => 'Mengatur jadwal, logistik, dan peserta dalam event tahunan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720038')->value('id_mahasiswa'),
                'nama_posisi' => 'Customer Support Intern',
                'perusahaan' => 'PT FastApp',
                'tanggal_mulai' => '2023-09-01',
                'tanggal_selesai' => '2023-12-31',
                'deskripsi' => 'Menangani pertanyaan dan keluhan pelanggan melalui email dan chat.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720232')->value('id_mahasiswa'),
                'nama_posisi' => 'Software Tester Intern',
                'perusahaan' => 'PT Digital Nusantara',
                'tanggal_mulai' => '2023-06-01',
                'tanggal_selesai' => '2023-08-31',
                'deskripsi' => 'Melakukan pengujian aplikasi mobile dan membuat laporan bug.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720089')->value('id_mahasiswa'),
                'nama_posisi' => 'Data Entry',
                'perusahaan' => 'CV Smart Solusindo',
                'tanggal_mulai' => '2023-05-01',
                'tanggal_selesai' => '2023-07-31',
                'deskripsi' => 'Memasukkan dan memverifikasi data pelanggan ke sistem perusahaan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720042')->value('id_mahasiswa'),
                'nama_posisi' => 'Panitia Seminar Nasional',
                'perusahaan' => 'Jurusan Teknologi Informasi',
                'tanggal_mulai' => '2023-11-01',
                'tanggal_selesai' => '2023-11-30',
                'deskripsi' => 'Bertanggung jawab pada sesi dokumentasi dan registrasi peserta.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720103')->value('id_mahasiswa'),
                'nama_posisi' => 'UI Designer Intern',
                'perusahaan' => 'StartApp Indonesia',
                'tanggal_mulai' => '2023-01-15',
                'tanggal_selesai' => '2023-03-15',
                'deskripsi' => 'Membantu tim desain membuat prototype aplikasi mobile.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720157')->value('id_mahasiswa'),
                'nama_posisi' => 'IT Support',
                'perusahaan' => 'SMK Bina Bangsa',
                'tanggal_mulai' => '2022-12-01',
                'tanggal_selesai' => '2023-03-01',
                'deskripsi' => 'Membantu instalasi dan perawatan jaringan komputer sekolah.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '244107023001')->value('id_mahasiswa'),
                'nama_posisi' => 'Frontend Developer Intern',
                'perusahaan' => 'PT Kreasi Digital',
                'tanggal_mulai' => '2023-02-01',
                'tanggal_selesai' => '2023-04-30',
                'deskripsi' => 'Mengembangkan antarmuka website menggunakan ReactJS.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720235')->value('id_mahasiswa'),
                'nama_posisi' => 'Asisten Praktikum',
                'perusahaan' => 'Polinema - TI',
                'tanggal_mulai' => '2023-09-01',
                'tanggal_selesai' => '2023-12-01',
                'deskripsi' => 'Membantu dosen dalam pelaksanaan praktikum Basis Data.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720043')->value('id_mahasiswa'),
                'nama_posisi' => 'IT Helpdesk',
                'perusahaan' => 'PT Fastnet Solusi',
                'tanggal_mulai' => '2023-03-01',
                'tanggal_selesai' => '2023-05-31',
                'deskripsi' => 'Menangani tiket kendala teknis dari karyawan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720124')->value('id_mahasiswa'),
                'nama_posisi' => 'Public Relations',
                'perusahaan' => 'Himpunan Mahasiswa TI',
                'tanggal_mulai' => '2023-01-10',
                'tanggal_selesai' => '2023-03-10',
                'deskripsi' => 'Mengelola komunikasi eksternal dan media sosial organisasi.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720194')->value('id_mahasiswa'),
                'nama_posisi' => 'Web Developer Freelance',
                'perusahaan' => 'Freelance',
                'tanggal_mulai' => '2023-06-01',
                'tanggal_selesai' => '2023-08-15',
                'deskripsi' => 'Membuat website company profile untuk klien lokal.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720099')->value('id_mahasiswa'),
                'nama_posisi' => 'Game Developer Intern',
                'perusahaan' => 'PT Gema Kreatif',
                'tanggal_mulai' => '2023-05-01',
                'tanggal_selesai' => '2023-07-31',
                'deskripsi' => 'Membuat game edukasi berbasis Unity untuk anak-anak.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720024')->value('id_mahasiswa'),
                'nama_posisi' => 'UI/UX Designer',
                'perusahaan' => 'PT Desain Inovatif',
                'tanggal_mulai' => '2023-04-01',
                'tanggal_selesai' => '2023-06-30',
                'deskripsi' => 'Mendesain tampilan aplikasi mobile berbasis Android.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720013')->value('id_mahasiswa'),
                'nama_posisi' => 'Network Technician',
                'perusahaan' => 'CV NetPro',
                'tanggal_mulai' => '2023-03-01',
                'tanggal_selesai' => '2023-05-01',
                'deskripsi' => 'Instalasi dan pemeliharaan jaringan LAN di sekolah-sekolah.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720237')->value('id_mahasiswa'),
                'nama_posisi' => 'Backend Developer',
                'perusahaan' => 'Startup Schedulify',
                'tanggal_mulai' => '2023-02-01',
                'tanggal_selesai' => '2023-04-15',
                'deskripsi' => 'Membangun API menggunakan Laravel dan MySQL.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720230')->value('id_mahasiswa'),
                'nama_posisi' => 'Social Media Manager',
                'perusahaan' => 'Event Organizer Kampus',
                'tanggal_mulai' => '2023-07-01',
                'tanggal_selesai' => '2023-09-01',
                'deskripsi' => 'Membuat konten dan menjadwalkan postingan di media sosial.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720167')->value('id_mahasiswa'),
                'nama_posisi' => 'Content Writer',
                'perusahaan' => 'PT Kata Digital',
                'tanggal_mulai' => '2023-06-01',
                'tanggal_selesai' => '2023-08-31',
                'deskripsi' => 'Menulis artikel SEO untuk website teknologi.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720082')->value('id_mahasiswa'),
                'nama_posisi' => 'IT Support',
                'perusahaan' => 'Universitas Polinema',
                'tanggal_mulai' => '2023-03-01',
                'tanggal_selesai' => '2023-06-01',
                'deskripsi' => 'Membantu instalasi software dan troubleshooting perangkat komputer.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720078')->value('id_mahasiswa'),
                'nama_posisi' => 'Data Analyst Intern',
                'perusahaan' => 'PT StatData',
                'tanggal_mulai' => '2023-05-15',
                'tanggal_selesai' => '2023-08-15',
                'deskripsi' => 'Menganalisis data transaksi penjualan menggunakan Excel dan Power BI.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720163')->value('id_mahasiswa'),
                'nama_posisi' => 'DevOps Assistant',
                'perusahaan' => 'CloudTech',
                'tanggal_mulai' => '2023-04-10',
                'tanggal_selesai' => '2023-07-10',
                'deskripsi' => 'Membantu dalam deployment aplikasi dan monitoring server.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720029')->value('id_mahasiswa'),
                'nama_posisi' => 'UI Designer Intern',
                'perusahaan' => 'Creative Labs',
                'tanggal_mulai' => '2023-02-15',
                'tanggal_selesai' => '2023-05-15',
                'deskripsi' => 'Membuat mockup desain untuk aplikasi mobile menggunakan Figma.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720062')->value('id_mahasiswa'),
                'nama_posisi' => 'Cybersecurity Intern',
                'perusahaan' => 'PT SecureNet',
                'tanggal_mulai' => '2023-03-10',
                'tanggal_selesai' => '2023-06-10',
                'deskripsi' => 'Menganalisis potensi kerentanan sistem dan membuat laporan keamanan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720149')->value('id_mahasiswa'),
                'nama_posisi' => 'Frontend Developer',
                'perusahaan' => 'PT WebKreatif',
                'tanggal_mulai' => '2023-05-01',
                'tanggal_selesai' => '2023-07-31',
                'deskripsi' => 'Mengembangkan antarmuka web responsif menggunakan ReactJS.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720030')->value('id_mahasiswa'),
                'nama_posisi' => 'Database Administrator',
                'perusahaan' => 'CV DataMania',
                'tanggal_mulai' => '2023-04-01',
                'tanggal_selesai' => '2023-06-30',
                'deskripsi' => 'Melakukan backup, maintenance, dan optimasi database MySQL.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_mahasiswa' => DB::table('mahasiswa')->where('nim', '2341720018')->value('id_mahasiswa'),
                'nama_posisi' => 'Web Developer',
                'perusahaan' => 'Freelance',
                'tanggal_mulai' => '2023-01-10',
                'tanggal_selesai' => '2023-03-15',
                'deskripsi' => 'Membuat website portofolio untuk klien menggunakan Laravel.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

}
