<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id_user' => '1',
                'username' => 'admin01',
                'password' => Hash::make('admin123'),
                'role' => 'admin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '2',
                'username' => '2341720172',
                'password' => Hash::make('2341720172'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '3',
                'username' => '2341720182',
                'password' => Hash::make('2341720182'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '4',
                'username' => '2341720234',
                'password' => Hash::make('2341720234'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '5',
                'username' => '2341720256',
                'password' => Hash::make('2341720256'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '6',
                'username' => '2341720187',
                'password' => Hash::make('2341720187'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '7',
                'username' => '2341720038',
                'password' => Hash::make('2341720038'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '8',
                'username' => '2341720232',
                'password' => Hash::make('2341720232'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '9',
                'username' => '2341720089',
                'password' => Hash::make('2341720089'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '10',
                'username' => '2341720042',
                'password' => Hash::make('2341720042'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '11',
                'username' => '2341720103',
                'password' => Hash::make('2341720103'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '12',
                'username' => '2341720157',
                'password' => Hash::make('2341720157'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '13',
                'username' => '244107023001',
                'password' => Hash::make('244107023001'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '14',
                'username' => '2341720235',
                'password' => Hash::make('2341720235'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '15',
                'username' => '2341720043',
                'password' => Hash::make('2341720043'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '16',
                'username' => '2341720124',
                'password' => Hash::make('2341720124'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '17',
                'username' => '2341720194',
                'password' => Hash::make('2341720194'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '18',
                'username' => '2341720099',
                'password' => Hash::make('2341720099'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '19',
                'username' => '2341720024',
                'password' => Hash::make('2341720024'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '20',
                'username' => '2341720013',
                'password' => Hash::make('2341720013'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '21',
                'username' => '2341720237',
                'password' => Hash::make('2341720237'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '22',
                'username' => '2341720230',
                'password' => Hash::make('2341720230'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '23',
                'username' => '2341720167',
                'password' => Hash::make('2341720167'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '24',
                'username' => '2341720082',
                'password' => Hash::make('2341720082'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '25',
                'username' => '2341720078',
                'password' => Hash::make('2341720078'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '26',
                'username' => '2341720163',
                'password' => Hash::make('2341720163'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '27',
                'username' => '2341720029',
                'password' => Hash::make('2341720029'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '28',
                'username' => '2341720062',
                'password' => Hash::make('2341720062'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '29',
                'username' => '2341720149',
                'password' => Hash::make('2341720149'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '30',
                'username' => '2341720030',
                'password' => Hash::make('2341720030'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '31',
                'username' => '2341720018',
                'password' => Hash::make('2341720018'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '32',
                'username' => 'admin02',
                'password' => Hash::make('admin123'),
                'role' => 'admin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '33',
                'username' => 'admin03',
                'password' => Hash::make('admin123'),
                'role' => 'admin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '34',
                'username' => '0028029101',
                'password' => Hash::make('0028029101'),
                'role' => 'dosen_pembimbing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '35',
                'username' => '0728099401',
                'password' => Hash::make('0728099401'),
                'role' => 'dosen_pembimbing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '36',
                'username' => '0014128704',
                'password' => Hash::make('0014128704'),
                'role' => 'dosen_pembimbing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '37',
                'username' => '0024088701',
                'password' => Hash::make('0024088701'),
                'role' => 'dosen_pembimbing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '38',
                'username' => '0013037905',
                'password' => Hash::make('0013037905'),
                'role' => 'dosen_pembimbing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '39',
                'username' => '0021059405',
                'password' => Hash::make('0021059405'),
                'role' => 'dosen_pembimbing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '40',
                'username' => '0002027214',
                'password' => Hash::make('0002027214'),
                'role' => 'dosen_pembimbing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '41',
                'username' => '0017129402',
                'password' => Hash::make('0017129402'),
                'role' => 'dosen_pembimbing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '42',
                'username' => '0008129002',
                'password' => Hash::make('0008129002'),
                'role' => 'dosen_pembimbing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '43',
                'username' => '0009118305',
                'password' => Hash::make('0009118305'),
                'role' => 'dosen_pembimbing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '44',
                'username' => '0006069202',
                'password' => Hash::make('0006069202'),
                'role' => 'dosen_pembimbing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '45',
                'username' => '0010068807',
                'password' => Hash::make('0010068807'),
                'role' => 'dosen_pembimbing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '46',
                'username' => '0009108402',
                'password' => Hash::make('0009108402'),
                'role' => 'dosen_pembimbing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => '47',
                'username' => '0716037502',
                'password' => Hash::make('0716037502'),
                'role' => 'dosen_pembimbing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
